roast-cms/analog-cafe-server

app/authentication/init.js, migrations/20170726114815-addTwitterIdToUser.js, models/postgres/user.js
ถ้า user เปลี่ยนข้อมูล profile ใน twitter เมื่อ authen จะสร้าง user ใหม่
=> fix duplicate create user

app/article/index.js, app/submission/index.js, models/mongo/article.js, models/mongo/submission.js
Add endpoint /list for Article API, and get an article by its slug. Remove category from article
and submission.
=> Add endpoint /list for Article API, and get

app/article/index.js, app/authentication/index.js, app/author/index.js, app/index.js, models/mongo/article.js, models/mongo/image.js, models/mongo/index.js, models/mongo/submission.js, package.json, seeds/02_articles.js, seeds/clean_db.js, yarn.lock
and format all code in app, models, and seeds
=> Specify version of dependencies, add lint, auto-formatting code on commit

app/article/index.js
=> Fix list api when author does not exist

app/submission/index.js, helpers/mailers/submission_updated.js, models/mongo/submission.js
=> Update sending submission status updated email to-

app/authentication/index.js, helpers/authenticate.js, helpers/mailer.js, helpers/mailers/sign_in.js
=> Update sign in email to use email template and

app/index.js, app/submission/index.js, helpers/redis.js, helpers/submission.js, models/mongo/image.js, package.json, yarn.lock
add submission upload progress API
=> Remove Websocket from uploading image progress and

app/api/index.js, app/article/index.js, app/authentication/index.js, app/submission/index.js
- /auth/twitter
- /auth/twitter/callback
- /auth/facebook
- /auth/facebook/callback
- /auth/email/verify
- /submissions
=> add api content

app/article/index.js, app/submission/index.js, helpers/submission.js
[word count](https://trello.com/c/88ZX1iK2/58-word-conunt)
=> use "composer-content-text" instead of fetch from raw content

app/authentication/index.js
[Improve login by email](https://trello.com/c/RueKnorY/56-improve-login-by-email)
Sending verify email once per min
=> improve email login

app/authentication/index.js
[token should be expired in few days](https://trello.com/c/K8DhIPa0/57-token-should-be-expired-in-few-days)
Token expired in 3 days
=> Token expired

helpers/submission.js
[improve article URL](https://trello.com/c/hGjtOhha/59-improve-article-url)
- title should be all lowercase
- add '-' between article title and id(random string)
=> improve submission slag

app/submission/index.js, helpers/submission.js, models/mongo/article.js, models/mongo/submission.js, models/mongo/user.js, package.json, yarn.lock
submission poster and fix timestamp to be
only date with UNIX format
=> Add post-date to Submission API, Fix

seeds/03_images.js
=> add detail to image seed

app/article/index.js
This will be used to give more context for the next article in line.
=> Detailed next article section

app/article/index.js
[Fixed] Editing article API that did not wait for finding a submission
=> [Fixed] Editing article API that did not wait for finding a submission

app/image/index.js, helpers/mailers/image_suggested.js
This PR fixes the author name in the email that they get when their image is being featured and also adds image URL to be displayed as `<img />` in the email.
=> Image feature email

app/author/index.js, package.json
Unpublishing rig is ready and deployed.
=> Unpublishing

app/article/article-feed.js, app/sitemap/index.js, app/submission/index.js
Update sitemap routes, hide rejected material from admins
=> Sitemap, names, view permissions

app/submission/index.js, helpers/mailer.js, models/mongo/submission.js
- Log all submission edits with user name and id
- Allow authors to edit and delete their submissions
=> Fixes and permissions

app/api/index.js, app/favourite/index.js, app/index.js, models/mongo/favourite.js
Lets registered users favourite articles they wish to endorse and read later.
=> Favourites tool

app/article/index.js, yarn.lock
- Security
- Avoid showing downloads in RSS
- Asc order for featured content iterable
=> Security, RSS, Features

app/article/index.js, app/submission/index.js, app/user/index.js, helpers/cache.js, models/mongo/index.js, package.json, yarn.lock
Reverts roast-cms/analog-cafe-server#369
=> Re-apply list caching with Redis

app/article/index.js, app/submission/index.js, app/user/index.js, helpers/cache.js, helpers/redis.js, models/mongo/index.js, package.json, yarn.lock
Reverts roast-cms/analog-cafe-server#371
=> Try redis caching via cachegoose again

package.json, yarn.lock
Reverts roast-cms/analog-cafe-server#376
=> Revert "Bump redis from 2.8.0 to 3.1.1"
